name: Build and Deploy Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Clean npm cache and install dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm cache clean --force
        npm install

    - name: Build Angular App
      run: npm run build
